version: "3.9"

networks:
  api-net:
    driver: bridge

volumes:
  postgres:
  api:

services:
  db:
    image: postgres:13.4
    container_name: db
    ports:
      - 5432:5432
    networks:
      - api-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data