# fly.toml app configuration file generated for assetizationapp on 2023-07-31T12:10:59-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "assetizationapp"
primary_region = "gru"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
