name: Run Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v3

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          envkey_DEBUG: false
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_ALGORITHM: ${{ vars.ALGORITHM }}
          envkey_ACCESS_TOKEN_EXPIRE_MINUTES: ${{ vars.ACCESS_TOKEN_EXPIRE_MINUTES || 30 }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false

      - name: Instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependências do projeto
        run: poetry install

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --format=github --target-version=py37 .
        continue-on-error: true

      - name: Rodar os testes
        run: poetry run task test --cov-report=xml

      - name: Subir cobertura para o codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}